INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Альфа-банк','YES', 'YES', 0, 'YES', 7900, 'YES', 'YES', 'YES', 'YES',  0, 2);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('ББР Банк','YES', 'YES', 0, 'YES', 800, 'NO', 'NO', 'NO', NULL, 0, 7);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Русский Стандарт','NO', 'NO', NULL, 'NO', NULL, 'YES', 'NO', 'NO', 'NO', NULL, 3);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Промсвязьбанк','YES', 'YES', 0, 'YES', 1800, 'YES', 'YES', 'NO', 'YES', 0, 4);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Трансстройбанк','YES', 'YES', 0, 'YES', 990, 'NO', 'NO', 'YES', 'YES', 0, 8);