INSERT INTO PERSONAL_CLIENT (NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,
INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISCS) VALUES ('Россельхозбанк','YES',0,'YES','YES',0,'YES',0,'YES',1.5,
'YES','YES',0,3);
INSERT INTO PERSONAL_CLIENT (NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,
INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISCS) VALUES ('Металлинвестбанк','YES',0,'YES','YES',0,'YES',680,'YES',1.6,
'YES','YES',0,4);
INSERT INTO PERSONAL_CLIENT (NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,
INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISCS) VALUES ('Авангард','YES',10000,'YES','YES',0,'YES',0,'YES',1.0,
'YES','YES',0,2);
INSERT INTO PERSONAL_CLIENT (NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,
INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISCS) VALUES ('ОТП','YES',15000,'YES','YES',50,'NO',0,'YES',1.7,
'YES','YES',0,5);
INSERT INTO PERSONAL_CLIENT (NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,
INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISCS) VALUES ('Восточный','YES',30000,'YES','YES',0,'NO',0,'YES',1.0,
'YES','YES',0,4);
