INSERT INTO PERSONAL_CLIENT (NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,
INTERNET_BANKING,DBO_PRICE,RISCS) VALUES ('Россельхозбанк','YES','YES',20000,'YES',0,'YES','NO','YES','YES',0,3);
INSERT INTO PERSONAL_CLIENT (NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,
INTERNET_BANKING,DBO_PRICE,RISCS) VALUES ('Металлинвестбанк','YES','YES',0,'YES',0,'YES','YES','NO','YES',0,4);
INSERT INTO PERSONAL_CLIENT (NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,
INTERNET_BANKING,DBO_PRICE,RISCS) VALUES ('Авангард','YES','YES',100000,'YES',0,'NO','NO','YES','YES',0,2);
INSERT INTO PERSONAL_CLIENT (NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,
INTERNET_BANKING,DBO_PRICE,RISCS) VALUES ('ОТП','YES','YES',100000,'YES',0,'NO','NO','YES','YES',0,5);
INSERT INTO PERSONAL_CLIENT (NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,
INTERNET_BANKING,DBO_PRICE,RISCS) VALUES ('Восточный','YES','YES',50000,'YES',0,'YES','YES','YES','YES',0,4);