INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('ГАЗПРОМБАНК','YES', '300','YES','YES', '300', 'YES', '0', 'YES', '1', 'YES', 'YES', '0', '4');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Тинькофф банк','YES', '0','YES','YES', '0', 'YES', '0', 'YES', '0', 'YES', 'YES', '0', '1');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('АК БАРС БАНК ','YES', '10000','YES','YES', '0', 'YES', '0', 'YES', '0.5', 'YES', 'YES', '0', '5');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Всероссийский банк развития регионов','YES', '700','YES','YES', '700', 'YES', '0', 'YES', '0.5', 'YES', 'YES', '0', '3');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Банк Возрождение','YES', '200','YES','YES', '200', 'YES', '0', 'YES', '1', 'YES', 'YES', '0', '2');