INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('ГАЗПРОМБАНК','YES', 'YES', '1000', 'YES', '3000', 'YES', 'YES', 'YES', 'YES', '1500', '4' );
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Тинькофф Банк','YES', 'YES', '100000', 'YES', '0', 'YES', 'NO', 'NO', 'YES', '0', '1' );
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('АК БАРС БАНК','YES', 'YES', '100000', 'YES', '500', 'YES', 'YES', 'YES', 'YES', '0', '5' );
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Всероссийский Банк Развития Регионов','YES', 'YES', '1800', 'YES', '800', 'YES', 'YES', 'YES', 'YES', '0', '3' );
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Банк Возрождение','YES', 'YES', '0', 'YES', '0', 'YES', 'YES', 'YES', 'YES', '0', '2' );