INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('ВТБ','YES', '0','YES','YES', '0', 'YES', '0', 'YES', '1.5', 'YES', 'YES', '25', '2');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Росбанк','YES', '0','YES','YES', '0', 'YES', '0', 'YES', '1.25', 'YES', 'YES', '0', '3');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Райффайзенбанк','YES', '0','YES','YES', '0', 'YES', '0', 'YES', '1.5', 'YES', 'YES', '0', '3');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Абсолют Банк','YES', '10000','YES','YES', '0', 'YES', '0', 'YES', '1', 'YES', 'YES', '15', '6');
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Связь-Банк','YES', '500','YES','YES', '0', 'YES', '0', 'YES', '1.5', 'YES', 'YES', '0', '5');