INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('ВТБ','YES', 'YES', 0, 'YES', 1900, 'NO', 'YES', 'YES', 'YES', 0, 2);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Росбанк','YES', 'YES', 0, 'YES', 490, 'YES', 'YES', 'YES', 'YES', 250, 3);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Райффайзенбанк','YES', 'YES', 0, 'YES', 990, 'YES', 'YES', 'YES', 'YES', 0, 3);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Абсолют Банк','YES', 'YES', 0, 'YES', 1000, 'YES', 'YES', 'YES', 'YES', 0, 6);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Связь-Банк','YES', 'YES', 0, 'YES', 2500, 'YES', 'NO', 'NO', 'YES', 0, 5);