CREATE TABLE IF NOT EXISTS PERSONAL_CLIENT(
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR (255) NOT NULL,
DEPOSIT BOOLEAN NOT NULL,
DEPOSIT_PRICE BIGINT,
CREDIT BOOLEAN NOT NULL,
ACCOUNT BOOLEAN NOT NULL,
ACCOUNT_PRICE BIGINT,
RKO BOOLEAN NOT NULL,
RKO_PRICE BIGINT,
MONEY_TRANSACTION BOOLEAN NOT NULL,
PERCENT FLOAT,
INTERNET_BANKING BOOLEAN NOT NULL,
MOBILE_BANKING BOOLEAN NOT NULL,
DBO_PRICE BIGINT,
RISKS BIGINT NOT NULL,
CONSTRAINT PERSONAL_CLIENT_PK PRIMARY KEY (ID)
);