ALTER TABLE PERSONAL_CLIENT MODIFY DEPOSIT VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY CREDIT VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY ACCOUNT VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY RKO VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY MONEY_TRANSACTION VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY INTERNET_BANKING VARCHAR(255);
ALTER TABLE PERSONAL_CLIENT MODIFY MOBILE_BANKING VARCHAR(255);