ALTER TABLE LEGAL_CLIENT MODIFY DEPOSIT VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY CREDIT VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY FACTORING VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY RKO VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY INVESTMENT VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY INTERNET_BANKING VARCHAR(255);
ALTER TABLE LEGAL_CLIENT MODIFY INTERNATIONAL_OP VARCHAR(255);