INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Фора-банк','YES','0','NO','YES','0','YES','0','YES','1','YES','YES','0','3');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('НБД-Банк','YES','400','NO','YES','250','YES','950','YES','0.9','YES','YES','500','1');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Совкомбанк','YES','0','YES','YES','3999','YES','0','YES','1.5','YES','YES','149','3');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Промсвязьбанк','YES','0','YES','YES','0','YES','0','YES','1.5','YES','YES','0','5');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Росгосстрах Банк','YES','0','YES','YES','500','YES','0','YES','0.6','YES','YES','0','3');