INSERT INTO LEGAL_CLIENT(NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,INTERNET_BANKING,DBO_PRICE,RISKS)
VALUES('Фора-банк','NO','YES','0','YES','890','NO','NO','NO','YES','0','4');
INSERT INTO LEGAL_CLIENT(NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,INTERNET_BANKING,DBO_PRICE,RISKS)
VALUES('НБД-Банк','NO','YES','0','YES','950','NO','NO','NO','YES','0','2');
INSERT INTO LEGAL_CLIENT(NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,INTERNET_BANKING,DBO_PRICE,RISKS)
VALUES('Совкомбанк','YES','YES','0','YES','650','NO','NO','NO','YES','0','1');
INSERT INTO LEGAL_CLIENT(NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,INTERNET_BANKING,DBO_PRICE,RISKS)
VALUES('Промсвязьбанк','NO','YES','400','YES','400','NO','NO','YES','YES','0','3');
INSERT INTO LEGAL_CLIENT(NAME,CREDIT,DEPOSIT,DEPOSIT_PRICE,RKO,RKO_PRICE,INVESTMENT,FACTORING,INTERNATIONAL_OP,INTERNET_BANKING,DBO_PRICE,RISKS)
VALUES('Росгосстрах Банк','YES','YES','1500','YES','1300','YES','NO','NO','YES','1300','4');