INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Уралсиб','YES','0','YES','YES','0','NO','0','YES','1,5','YES','YES','600','1');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Сбербанк','YES','0','YES','YES','0','YES','0','YES','0','YES','YES','0','3');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Саровбизнесбанк','YES','0','YES','YES','0','YES','0','YES','0','YES','YES','0','6');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('МТС-Банк','YES','0','YES','NO','0','NO','0','YES','0','YES','YES','0','4');
INSERT INTO PERSONAL_CLIENT(NAME,DEPOSIT,DEPOSIT_PRICE,CREDIT,ACCOUNT,ACCOUNT_PRICE,RKO,RKO_PRICE,MONEY_TRANSACTION,PERCENT,INTERNET_BANKING,MOBILE_BANKING,DBO_PRICE,RISKS)
VALUES('Локо Банк','NO','0','YES','YES','0','NO','0','YES','0','YES','YES','0','5');
