

INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Уралсиб','YES','YES',0,'YES',480,'YES','YES','YES','YES',0,1);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Сбербанк','YES','YES',0,'YES',1800,'YES','YES','YES','YES',0,3);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('Саровбизнесбанк','YES','YES',0,'YES',800,'NO','NO','YES','YES',0,6);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
VALUES('МТС-Банк','YES','YES',0,'YES',0,YES,YES,YES,YES,0,4);
INSERT INTO LEGAL_CLIENT(NAME, CREDIT, DEPOSIT, DEPOSIT_PRICE, RKO, RKO_PRICE, INVESTMENT, FACTORING, INTERNATIONAL_OP, INTERNET_BANKING, DBO_PRICE, RISKS)
