INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Альфа-банк', 'YES', 0, 'YES', 'YES', 0, 'NO', NULL, 'YES', 0.7, 'YES', 'YES', 0, 2);
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('ББР Банк', 'YES', 0, 'YES', 'YES', 0, 'YES', 0, 'YES', 1.3, 'YES', 'YES', 0, 7);
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Русский Стандарт', 'YES', 0, 'YES', 'YES', 0, 'NO', NULL, 'YES', 1, 'YES', 'YES', 0, 3);
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Промсвязьбанк', 'YES', 0, 'YES', 'YES', 0, 'YES', 0, 'YES', 1, 'YES', 'YES', 0, 4);
INSERT INTO PERSONAL_CLIENT(NAME, DEPOSIT, DEPOSIT_PRICE, CREDIT, ACCOUNT, ACCOUNT_PRICE, RKO, RKO_PRICE, MONEY_TRANSACTION, PERCENT, INTERNET_BANKING, MOBILE_BANKING, DBO_PRICE, RISKS)
VALUES('Трансстройбанк', 'YES', 0, 'YES', 'YES', 0, 'NO', NULL, 'YES', 1.3, 'YES', 'YES', 0, 8);